### ISSUE TITLE
framework.messenger config error since symfony 4.3.1

### ISSUE THREAD

**Issue by nils-m** [Sylius/InvoicingPlugin#145]
Hello,
Upgraded Sylius to 1.5.1 SF 1.5.1 via composer.
Had this error:
`Invalid configuration for path "framework.messenger": You must specify the "default_bus" if you define more than one bus.`

Setting a _default_bus_ in /vendor/sylius/invoicing-plugin/src/Resources/config/config.yml
fixed the issue. 

```yaml
framework:
     messenger:
        default_bus: sylius_invoicing_plugin.command_bus
        buses:
            sylius_invoicing_plugin.command_bus: ~
            sylius_invoicing_plugin.event_bus:
                default_middleware: allow_no_handlers
```

Or better in _{App}/config/packages/messenger.yaml_ until fixed in this plugin.
```yaml
framework:
    messenger:
        default_bus: sylius_invoicing_plugin.command_bus
```
