### ISSUE TITLE
Extending Invoice

### ISSUE THREAD

**Issue by antonioperic** [Sylius/InvoicingPlugin#152]
Hi,
I am using dev-master of plugin and dev-master of Sylius.

I added this to config

```
sylius_invoicing:
    resources:
        invoice:
            classes:
                model: App\Entity\Invoice\Invoice
```
and this is my new entity, there is nothing inside

```
<?php

declare(strict_types=1);

namespace App\Entity\Invoice;

use Doctrine\ORM\Mapping as ORM;
use Sylius\InvoicingPlugin\Entity\Invoice as BaseInvoice;

/**
 * @ORM\Entity
 * @ORM\Table(name="sylius_invoicing_plugin_invoice")
 */
class Invoice extends BaseInvoice
{
}

```

i am getting this errror

> Return value of Sylius\InvoicingPlugin\Entity\Invoice::channel() must be an instance of Sylius\InvoicingPlugin\Entity\InvoiceChannelInterface, null returned

I understand that the problem is with embedded properties, but I am not figuring out how to solve this.
