### ISSUE TITLE
generate migration to wrong path

### ISSUE THREAD

**Issue by imajim** [Sylius/InvoicingPlugin#192]
Hello,

Sylius 1.8.4
symfony 4.4.16
doctrine 3.0

my doctrine_migrations.yaml:
```
doctrine_migrations:
    migrations_paths:
        'App\Migrations': "%kernel.project_dir%/src/Migrations"
    storage:
        table_storage:
            table_name: sylius_migrations
```

after installation  invoicingPlugin all generated migration, are going to /vendor/sylius/invoicing-plugin/src/Migrations
