### ISSUE TITLE
Add fixtures abilities

### ISSUE THREAD

**Issue by Prometee** [Sylius/InvoicingPlugin#72]
It could be great if we could add channel extra informations in a fixture.

Exemple :
```
sylius_fixtures:
    suites:
        my_own_fixture:

            listeners:
                orm_purger: ~
                logger: ~

            fixtures:

                channel:
                    options:
                        custom:
                            default_web_store:
                                enabled: true
                                name: "Web Store"
                                code: "default"
                                contact_email: "support@exemple.com"
                                default_locale: "%locale%"
                                hostname: null
                                locales:
                                    - "en_US"
                                    - "fr_FR"
                                    - "es_ES"
                                    - "de_DE"
                                base_currency: "USD"
                                currencies:
                                    - "USD"
                                    - "EUR"
                                billing_data:
                                    company: 'My company'
                                    country_code: 'US'
                                    city: 'My city'
                                    postcode: '00000'
                                    tax_id: '1234567890'
                                    street_address: '1 my street address'
```
