### ISSUE TITLE
Resending invoice use wrong locale

### ISSUE THREAD

**Issue by Gounlaf** [Sylius/InvoicingPlugin#81]
Hi,

In administration panel, when resending the invoice, the locale used is the one from the current logged user (administrator), and not the invoice locale.

I didn't investigate the code. I might do a PR (but don't know when)

**Comment by bartoszpietrzak1994** [comment]
Hello Gounlaf,

which version of InvoicingPlugin do you use in your project? I investigated the code and locale used to be taken from the current logged administrator but it was fixed in `0.3.1` version.

**Comment by Zales0123** [comment]
Hello Levis, did you check out a possible solution that @bartoszpietrzak1994 proposed? :)

**Comment by Gounlaf** [comment]
Hi,

Sorry, I've not checked yet. I will do soon.

**Comment by Gounlaf** [comment]
Hi @bartoszpietrzak1994, @Zales0123,

I was using (and still use) the latest tagged version 0.6.0.
I override the default provided template with mine. I didn't find any method to do so, so I reconfigure the service, injecting my template path

```yaml
    myapp.invoice.pdf_file_generator:
        class: Sylius\InvoicingPlugin\Generator\InvoicePdfFileGenerator
        decorates: Sylius\InvoicingPlugin\Generator\InvoicePdfFileGenerator
        arguments:
            - '@Sylius\InvoicingPlugin\Repository\InvoiceRepository'
            - '@sylius.repository.channel'
            - '@templating.engine.twig'
            - '@knp_snappy.pdf'
            - 'invoice/pdf.html.twig'
```

I first thank it was the problem, but returning to default configuration didn't fix the issue.

I'm using the default key provided in original template, translated with `trans`.
I've just changed html/css, nothing else =/
